
/* SPI Flash DMA registers */

#define SPI_FLASH_BASE 		0x4000
#define SPI_FLASH_ADDR_LO 	(SPI_FLASH_BASE + 0)
#define SPI_FLASH_ADDR_HI 	(SPI_FLASH_BASE + 1)
#define SPI_FLASH_CMD		(SPI_FLASH_BASE + 2)
#define SPI_FLASH_DATA		(SPI_FLASH_BASE + 3)
#define SPI_FLASH_STATUS	(SPI_FLASH_BASE + 4)
#define SPI_FLASH_DMA_ADDR  (SPI_FLASH_BASE + 5)
#define SPI_FLASH_DMA_COUNT (SPI_FLASH_BASE + 6)

